version: '3.9'
services:
  frontend:
    build: ./frontend
    command: pnpm dev
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=fireandfork
      - POSTGRES_USER=fireandfork
      - POSTGRES_PASSWORD=fireandfork
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: fireandfork
      POSTGRES_USER: fireandfork
      POSTGRES_PASSWORD: fireandfork
    ports:
      - '5432:5432'
