name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: fireandfork
          POSTGRES_USER: fireandfork
          POSTGRES_PASSWORD: fireandfork
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install frontend deps
        run: |
          cd frontend
          pnpm install
      - name: Frontend build
        run: |
          cd frontend
          pnpm build
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          cd backend
          pip install django djangorestframework
      - name: Backend tests
        run: |
          cd backend
          python manage.py test
